services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: skud_admin
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: domophone_db
    volumes:
      - domophone_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - domnet
    container_name: dom_db

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - domnet
    container_name: mqtt_broker

  emulator:
    build:
      context: .
      dockerfile: emulator/Dockerfile
    depends_on:
      - mqtt-broker
      - web
    networks:
      - domnet
    container_name: dom_emulator

  web:
    build:
      context: .
      dockerfile: web_server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mqtt-broker
      - db
    networks:
      - domnet
    container_name: web_api

volumes:
  domophone_data:

networks:
  domnet:
    name: skud_network
    driver: bridge