services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - domophone_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - domnet
    container_name: dom_db

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "${MQTT_PORT_EXTERNAL}:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - domnet
    container_name: mqtt_broker

  emulator:
    build:
      context: .
      dockerfile: emulator/Dockerfile
    depends_on:
      - mqtt-broker
      - web
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - domnet
    container_name: dom_emulator

  web:
    build:
      context: .
      dockerfile: web_server/Dockerfile
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - mqtt-broker
      - db
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - domnet
    container_name: web_api

volumes:
  domophone_data:

networks:
  domnet:
    name: skud_network
    driver: bridge