"""Create domophones and events tables

Revision ID: 36e872754203
Revises: 
Create Date: 2025-06-30 16:00:28.862683

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e872754203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domophone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_adress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('door_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keys', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domophone_mac_adress'), 'domophone', ['mac_adress'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_adress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_mac_adress'), 'event', ['mac_adress'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_mac_adress'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_domophone_mac_adress'), table_name='domophone')
    op.drop_table('domophone')
    # ### end Alembic commands ###
